name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest Rust nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install libtiff-dev libopenimageio-dev
    - name: Default
      run: make test
    #- name: OpenImageIO
    #run: make test backend=openimageio
