name: Build MacOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest Rust nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
    - name: Dependencies
      run: brew install tiff openimageio
    - name: Default
      run: make test
    - name: Rust
      run: make test backend=rust
    - name: OpenImageIO
      run: make test backend=openimageio
